name: Generate Pac-Man Contribution Graph

on:
  # Roda a cada 12 horas
  schedule:
    - cron: '0 */12 * * *'
  # Permite que você rode manualmente pela aba "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pac-Man Graph

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Pac-Man
        # Esta é a Action correta para o Pac-Man
        uses: ThaUnknown/pacman-contribution-graph@v2.0.0
        with:
          # Pega o seu nome de usuário automaticamente
          github_user_name: ${{ github.repository_owner }}
          
          # Caminho e nome do arquivo que será gerado
          file_path: "dist/pacman.svg"
          
          # Token necessário para a Action fazer o commit no seu repositório
          github_token: ${{ secrets.GITHUB_TOKEN }}
