name: Generate Pac-Man Contribution Graph

on:
  # Gatilhos: Roda a cada 12 horas, manualmente, ou em cada push para a branch main
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    # Permissão para a Action poder fazer commit no seu repositório
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Clona o seu repositório para a máquina virtual do robô
      - uses: actions/checkout@v4

      # Passo 2: Roda a Action do Pac-Man
      - name: Generate Pac-Man Graph
        uses: abozanona/pacman-contribution-graph@main # A action que você encontrou
        with:
          # Pega seu nome de usuário automaticamente
          github_user_name: ${{ github.repository_owner }}

          # O token é passado para que a action tenha permissão para fazer o commit
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Define o nome da pasta onde a imagem será salva
          outputs_dir: dist
