name: Generate Pac-Man Contribution Graph

on:
  # Roda a cada 12 horas
  schedule:
    - cron: '0 */12 * * *'
  # Permite que você rode manualmente pela aba "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pac-Man Graph

    # Concede permissão para o robô fazer commit no seu repositório
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Pac-Man
        uses: platane/snk@v3 # Esta é a action que gera o gráfico animado
        with:
          # O SEU usuário do GitHub
          github_user_name: ${{ github.repository_owner }}

          # Arquivos de saída
          # O ?palette=github-dark no final gera a versão para tema escuro
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add dist
          git commit -m "chore: update contribution graph"
          git push
